"""Initial migration

Revision ID: dad913e0698e
Revises: 0cfee5e97701
Create Date: 2025-09-08 19:24:43.609291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad913e0698e'
down_revision = '0cfee5e97701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
